// Mock seed data for Smart Job Tracker
import { generateId } from '../utils/helpers';

export const MOCK_APPLICATIONS = [
    {
        id: generateId(),
        company: 'Google',
        role: 'Senior Software Engineer',
        location: 'Mountain View, CA',
        locationType: 'hybrid',
        salaryMin: 180000,
        salaryMax: 240000,
        platform: 'LinkedIn',
        status: 'interviewing',
        appliedDate: '2026-03-10',
        interviewDate: '2026-03-28',
        notes: 'Had a great initial screen. Technical round scheduled. Need to review system design patterns.',
        bookmarked: true,
    },
    {
        id: generateId(),
        company: 'Meta',
        role: 'Frontend Engineer',
        location: 'Menlo Park, CA',
        locationType: 'onsite',
        salaryMin: 170000,
        salaryMax: 220000,
        platform: 'Company Website',
        status: 'applied',
        appliedDate: '2026-03-12',
        interviewDate: null,
        notes: 'Applied through referral from college friend.',
        bookmarked: false,
    },
    {
        id: generateId(),
        company: 'Stripe',
        role: 'Full Stack Developer',
        location: 'Remote',
        locationType: 'remote',
        salaryMin: 160000,
        salaryMax: 200000,
        platform: 'LinkedIn',
        status: 'offer',
        appliedDate: '2026-02-20',
        interviewDate: '2026-03-05',
        notes: 'Received offer! $175k base + equity. Need to negotiate.',
        bookmarked: true,
    },
    {
        id: generateId(),
        company: 'Microsoft',
        role: 'React Developer',
        location: 'Seattle, WA',
        locationType: 'hybrid',
        salaryMin: 150000,
        salaryMax: 190000,
        platform: 'LinkedIn',
        status: 'rejected',
        appliedDate: '2026-02-15',
        interviewDate: '2026-02-28',
        notes: 'Rejected after final round. Feedback: needed stronger system design skills.',
        bookmarked: false,
    },
    {
        id: generateId(),
        company: 'Airbnb',
        role: 'Software Engineer II',
        location: 'San Francisco, CA',
        locationType: 'onsite',
        salaryMin: 165000,
        salaryMax: 210000,
        platform: 'Company Website',
        status: 'applied',
        appliedDate: '2026-03-18',
        interviewDate: null,
        notes: 'Applied directly. Waiting for HR response.',
        bookmarked: true,
    },
    {
        id: generateId(),
        company: 'Netflix',
        role: 'Senior Frontend Engineer',
        location: 'Los Gatos, CA',
        locationType: 'hybrid',
        salaryMin: 200000,
        salaryMax: 280000,
        platform: 'Indeed',
        status: 'interviewing',
        appliedDate: '2026-03-08',
        interviewDate: '2026-03-30',
        notes: 'Passed the coding screen. Onsite loop scheduled for next week.',
        bookmarked: true,
    },
    {
        id: generateId(),
        company: 'Uber',
        role: 'Software Engineer',
        location: 'Remote',
        locationType: 'remote',
        salaryMin: 145000,
        salaryMax: 185000,
        platform: 'Referral',
        status: 'applied',
        appliedDate: '2026-03-20',
        interviewDate: null,
        notes: 'Referred by a friend from the San Francisco office.',
        bookmarked: false,
    },
    {
        id: generateId(),
        company: 'Spotify',
        role: 'Mobile Engineer (React Native)',
        location: 'Remote',
        locationType: 'remote',
        salaryMin: 140000,
        salaryMax: 175000,
        platform: 'LinkedIn',
        status: 'applied',
        appliedDate: '2026-03-22',
        interviewDate: null,
        notes: 'Love their engineering blog. Would be a dream job.',
        bookmarked: true,
    },
    {
        id: generateId(),
        company: 'Shopify',
        role: 'Senior React Developer',
        location: 'Remote',
        locationType: 'remote',
        salaryMin: 155000,
        salaryMax: 195000,
        platform: 'Company Website',
        status: 'rejected',
        appliedDate: '2026-02-10',
        interviewDate: '2026-02-20',
        notes: 'Rejected after HR screen. Position was filled internally.',
        bookmarked: false,
    },
    {
        id: generateId(),
        company: 'Figma',
        role: 'Frontend Engineer, Design Systems',
        location: 'San Francisco, CA',
        locationType: 'hybrid',
        salaryMin: 160000,
        salaryMax: 205000,
        platform: 'AngelList',
        status: 'applied',
        appliedDate: '2026-03-24',
        interviewDate: null,
        notes: 'Applied via AngelList. Very excited about this role!',
        bookmarked: true,
    },
    {
        id: generateId(),
        company: 'GitHub',
        role: 'Staff Engineer',
        location: 'Remote',
        locationType: 'remote',
        salaryMin: 210000,
        salaryMax: 260000,
        platform: 'LinkedIn',
        status: 'interviewing',
        appliedDate: '2026-03-01',
        interviewDate: '2026-03-27',
        notes: 'Talking to the engineering manager next week.',
        bookmarked: false,
    },
    {
        id: generateId(),
        company: 'Notion',
        role: 'Product Engineer',
        location: 'San Francisco, CA',
        locationType: 'hybrid',
        salaryMin: 150000,
        salaryMax: 185000,
        platform: 'Company Website',
        status: 'saved',
        appliedDate: null,
        interviewDate: null,
        notes: 'Interested but not ready to apply yet. Waiting for a good time.',
        bookmarked: true,
    },
];

export const STATUSES = [
    { value: 'all', label: 'All Statuses' },
    { value: 'applied', label: 'Applied' },
    { value: 'interviewing', label: 'Interviewing' },
    { value: 'offer', label: 'Offer' },
    { value: 'rejected', label: 'Rejected' },
    { value: 'saved', label: 'Saved' },
];

export const PLATFORMS = [
    { value: 'all', label: 'All Platforms' },
    { value: 'LinkedIn', label: 'LinkedIn' },
    { value: 'Company Website', label: 'Company Website' },
    { value: 'Indeed', label: 'Indeed' },
    { value: 'Referral', label: 'Referral' },
    { value: 'AngelList', label: 'AngelList' },
    { value: 'Glassdoor', label: 'Glassdoor' },
    { value: 'Other', label: 'Other' },
];

export const LOCATION_TYPES = [
    { value: 'all', label: 'All Types' },
    { value: 'remote', label: 'Remote' },
    { value: 'onsite', label: 'Onsite' },
    { value: 'hybrid', label: 'Hybrid' },
];

export const SORT_OPTIONS = [
    { value: 'date-desc', label: 'Newest First' },
    { value: 'date-asc', label: 'Oldest First' },
    { value: 'salary-desc', label: 'Salary: High → Low' },
    { value: 'salary-asc', label: 'Salary: Low → High' },
    { value: 'company', label: 'Company A–Z' },
];
